<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AssemblyName>SystemVerifyKnowledge.CoreLib</AssemblyName>
    <RootNamespace>SystemVerifyKnowledge.CoreLib</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SystemVerifyKnowledge.Common\SystemVerifyKnowledge.Common.csproj" />
  </ItemGroup>

</Project>
