<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AssemblyName>SystemVerifyKnowledge.Database.Result</AssemblyName>
    <RootNamespace>SystemVerifyKnowledge.Database.Result</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="5.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SystemVerifyKnowledge.Common\SystemVerifyKnowledge.Common.csproj" />
    <ProjectReference Include="..\SystemVerifyKnowledge.CoreLib\SystemVerifyKnowledge.CoreLib.csproj" />
    <ProjectReference Include="..\SystemVerifyKnowledge.Database\SystemVerifyKnowledge.Database.csproj" />
  </ItemGroup>

</Project>
